Feat/update deps
MateriApps/OpenCord pull request #51
Opened 2022-06-04 08:52 UTC by X1nto

2022-06-18 01:59 UTC, DiamondMiner88 approved these changes

2022-08-10 21:15 UTC, DiamondMiner88 requested changes
Wasn't there an even newer compose version released today btw?
Also it seems like the overlapping panels are significantly more smooth compared to master currently.

2022-08-11 04:42 UTC, X1nto commented
> Wasn't there an even newer compose version released today btw? 
yup, epic timing
> Also it seems like the overlapping panels are significantly more smooth compared to master currently.
Didn't really notice anything, maybe because I just wasn't looking. They probably optimized something in compose drawing

2022-08-11 14:15 UTC, DiamondMiner88 approved these changes

2022-08-11 14:57 UTC, merged